// All study content extracted from the course PDFs (lessons 6–10 + sample paper + topics)
const DATA = {
  examDate: "2026-06-16",

  // ===== PART 1: English -> Chinese vocabulary =====
  vocab: [
    // From the sample paper
    { en: "classroom", zh: "教室", py: "jiàoshì", cat: "Places" },
    { en: "police", zh: "警察", py: "jǐngchá", cat: "Jobs" },
    { en: "to buy a cellphone", zh: "买手机", py: "mǎi shǒujī", cat: "Phrases" },
    { en: "Oct. 3rd", zh: "10月3号", py: "shí yuè sān hào", cat: "Dates" },
    { en: "There are some books on the table.", zh: "桌子上面有一些书。", py: "Zhuōzi shàngmiàn yǒu yìxiē shū.", cat: "Sentences" },
    // Abilities
    { en: "to sing", zh: "唱歌", py: "chànggē", cat: "Abilities" },
    { en: "to dance", zh: "跳舞", py: "tiàowǔ", cat: "Abilities" },
    { en: "to play basketball", zh: "打篮球", py: "dǎ lánqiú", cat: "Abilities" },
    { en: "to play football", zh: "踢足球", py: "tī zúqiú", cat: "Abilities" },
    { en: "to cook", zh: "做饭", py: "zuòfàn", cat: "Abilities" },
    { en: "to drive", zh: "开车", py: "kāichē", cat: "Abilities" },
    { en: "to swim", zh: "游泳", py: "yóuyǒng", cat: "Abilities" },
    { en: "to write Chinese characters", zh: "写汉字", py: "xiě Hànzì", cat: "Abilities" },
    // Languages
    { en: "Chinese (language)", zh: "中文 / 汉语", py: "Zhōngwén / Hànyǔ", cat: "Languages" },
    { en: "English (language)", zh: "英语", py: "Yīngyǔ", cat: "Languages" },
    { en: "Turkish (language)", zh: "土耳其语", py: "Tǔ'ěrqíyǔ", cat: "Languages" },
    { en: "French (language)", zh: "法语", py: "Fǎyǔ", cat: "Languages" },
    { en: "German (language)", zh: "德语", py: "Déyǔ", cat: "Languages" },
    { en: "Spanish (language)", zh: "西班牙语", py: "Xībānyáyǔ", cat: "Languages" },
    { en: "Russian (language)", zh: "俄语", py: "Éyǔ", cat: "Languages" },
    { en: "Arabic (language)", zh: "阿拉伯语", py: "Ālābóyǔ", cat: "Languages" },
    // Food
    { en: "sushi", zh: "寿司", py: "shòusī", cat: "Food" },
    { en: "bread", zh: "面包", py: "miànbāo", cat: "Food" },
    { en: "steamed bun", zh: "馒头", py: "mántou", cat: "Food" },
    { en: "rice", zh: "米饭", py: "mǐfàn", cat: "Food" },
    { en: "steak", zh: "牛排", py: "niúpái", cat: "Food" },
    { en: "pasta", zh: "意面", py: "yìmiàn", cat: "Food" },
    { en: "noodles", zh: "面条儿", py: "miàntiáor", cat: "Food" },
    { en: "hamburger", zh: "汉堡", py: "hànbǎo", cat: "Food" },
    { en: "pizza", zh: "披萨", py: "pīsà", cat: "Food" },
    { en: "roasted meat / kebab", zh: "烤肉", py: "kǎoròu", cat: "Food" },
    { en: "Turkish food", zh: "土耳其菜", py: "Tǔ'ěrqí cài", cat: "Food" },
    // Drinks
    { en: "coffee", zh: "咖啡", py: "kāfēi", cat: "Drinks" },
    { en: "tea", zh: "茶", py: "chá", cat: "Drinks" },
    { en: "milk", zh: "牛奶", py: "niúnǎi", cat: "Drinks" },
    { en: "juice", zh: "果汁", py: "guǒzhī", cat: "Drinks" },
    { en: "water", zh: "水", py: "shuǐ", cat: "Drinks" },
    { en: "cola", zh: "可乐", py: "kělè", cat: "Drinks" },
    { en: "beer", zh: "啤酒", py: "píjiǔ", cat: "Drinks" },
    { en: "red wine", zh: "红酒", py: "hóngjiǔ", cat: "Drinks" },
    // Time words
    { en: "yesterday", zh: "昨天", py: "zuótiān", cat: "Time" },
    { en: "today", zh: "今天", py: "jīntiān", cat: "Time" },
    { en: "tomorrow", zh: "明天", py: "míngtiān", cat: "Time" },
    { en: "last year", zh: "去年", py: "qùnián", cat: "Time" },
    { en: "this year", zh: "今年", py: "jīnnián", cat: "Time" },
    { en: "next year", zh: "明年", py: "míngnián", cat: "Time" },
    { en: "last month", zh: "上个月", py: "shàng ge yuè", cat: "Time" },
    { en: "this month", zh: "这个月", py: "zhè ge yuè", cat: "Time" },
    { en: "next month", zh: "下个月", py: "xià ge yuè", cat: "Time" },
    { en: "last week", zh: "上个星期", py: "shàng ge xīngqī", cat: "Time" },
    { en: "this week", zh: "这个星期", py: "zhè ge xīngqī", cat: "Time" },
    { en: "next week", zh: "下个星期", py: "xià ge xīngqī", cat: "Time" },
    { en: "birthday", zh: "生日", py: "shēngrì", cat: "Time" },
    // Places
    { en: "school", zh: "学校", py: "xuéxiào", cat: "Places" },
    { en: "supermarket", zh: "超市", py: "chāoshì", cat: "Places" },
    { en: "restaurant", zh: "饭店", py: "fàndiàn", cat: "Places" },
    { en: "coffee shop", zh: "咖啡店", py: "kāfēi diàn", cat: "Places" },
    { en: "library", zh: "图书馆", py: "túshūguǎn", cat: "Places" },
    { en: "bank", zh: "银行", py: "yínháng", cat: "Places" },
    { en: "home", zh: "家", py: "jiā", cat: "Places" },
    { en: "dormitory", zh: "宿舍", py: "sùshè", cat: "Places" },
    { en: "hospital", zh: "医院", py: "yīyuàn", cat: "Places" },
    { en: "police station", zh: "警察局", py: "jǐngchá jú", cat: "Places" },
    { en: "shop / store", zh: "商店", py: "shāngdiàn", cat: "Places" },
    // Jobs
    { en: "teacher", zh: "老师", py: "lǎoshī", cat: "Jobs" },
    { en: "doctor", zh: "医生", py: "yīshēng", cat: "Jobs" },
    { en: "student", zh: "学生", py: "xuéshēng", cat: "Jobs" },
    { en: "salesperson", zh: "售货员", py: "shòuhuòyuán", cat: "Jobs" },
    { en: "waiter / server", zh: "服务员", py: "fúwùyuán", cat: "Jobs" },
    // Objects with measure words
    { en: "a cup / glass", zh: "一个杯子", py: "yí ge bēizi", cat: "Objects" },
    { en: "a notebook", zh: "一个笔记本", py: "yí ge bǐjìběn", cat: "Objects" },
    { en: "a shirt", zh: "一件衬衫", py: "yí jiàn chènshān", cat: "Objects" },
    { en: "a cake", zh: "一个蛋糕", py: "yí ge dàngāo", cat: "Objects" },
    { en: "a pen", zh: "一支笔", py: "yì zhī bǐ", cat: "Objects" },
    { en: "a bottle of cola", zh: "一瓶可乐", py: "yì píng kělè", cat: "Objects" },
    { en: "a book", zh: "一本书", py: "yì běn shū", cat: "Objects" },
    { en: "an umbrella", zh: "一把伞", py: "yì bǎ sǎn", cat: "Objects" },
    { en: "a bed", zh: "一张床", py: "yì zhāng chuáng", cat: "Objects" },
    { en: "a chair", zh: "一把椅子", py: "yì bǎ yǐzi", cat: "Objects" },
    { en: "a table / desk", zh: "一个桌子", py: "yí ge zhuōzi", cat: "Objects" },
    { en: "wardrobe", zh: "衣柜", py: "yīguì", cat: "Objects" },
    { en: "pillow", zh: "枕头", py: "zhěntou", cat: "Objects" },
    { en: "quilt / blanket", zh: "被子", py: "bèizi", cat: "Objects" },
    { en: "clothes", zh: "衣服", py: "yīfu", cat: "Objects" },
    { en: "schoolbag", zh: "书包", py: "shūbāo", cat: "Objects" },
    { en: "cellphone", zh: "手机", py: "shǒujī", cat: "Objects" },
    { en: "kitten / cat", zh: "小猫", py: "xiǎomāo", cat: "Objects" },
    // Wallet topic
    { en: "wallet", zh: "钱包", py: "qiánbāo", cat: "Wallet" },
    { en: "money", zh: "钱", py: "qián", cat: "Wallet" },
    { en: "bank card", zh: "银行卡", py: "yínháng kǎ", cat: "Wallet" },
    { en: "photo", zh: "照片", py: "zhàopiàn", cat: "Wallet" },
    { en: "ID card", zh: "身份证", py: "shēnfènzhèng", cat: "Wallet" },
    { en: "driver's license", zh: "驾照", py: "jiàzhào", cat: "Wallet" },
    { en: "transport card", zh: "交通卡", py: "jiāotōng kǎ", cat: "Wallet" },
    { en: "campus card", zh: "校园卡", py: "xiàoyuán kǎ", cat: "Wallet" },
    // Position words
    { en: "on / above", zh: "上面", py: "shàngmiàn", cat: "Positions" },
    { en: "under / below", zh: "下面", py: "xiàmiàn", cat: "Positions" },
    { en: "in front", zh: "前面", py: "qiánmiàn", cat: "Positions" },
    { en: "behind", zh: "后面", py: "hòumiàn", cat: "Positions" },
    { en: "left side", zh: "左面", py: "zuǒmiàn", cat: "Positions" },
    { en: "right side", zh: "右面", py: "yòumiàn", cat: "Positions" },
    { en: "middle", zh: "中间", py: "zhōngjiān", cat: "Positions" },
    { en: "inside", zh: "里面", py: "lǐmiàn", cat: "Positions" },
    { en: "outside", zh: "外面", py: "wàimiàn", cat: "Positions" },
    // Verb phrases (去 + place + purpose)
    { en: "to buy things", zh: "买东西", py: "mǎi dōngxi", cat: "Phrases" },
    { en: "to take class", zh: "上课", py: "shàngkè", cat: "Phrases" },
    { en: "to do homework", zh: "写作业", py: "xiě zuòyè", cat: "Phrases" },
    { en: "to eat a meal", zh: "吃饭", py: "chīfàn", cat: "Phrases" },
    { en: "to drink coffee", zh: "喝咖啡", py: "hē kāfēi", cat: "Phrases" },
    { en: "to read a book", zh: "看书", py: "kàn shū", cat: "Phrases" },
    { en: "to withdraw money", zh: "取钱", py: "qǔ qián", cat: "Phrases" },
    { en: "to sleep", zh: "睡觉", py: "shuìjiào", cat: "Phrases" },
    { en: "to go to the supermarket to buy things", zh: "去超市买东西", py: "qù chāoshì mǎi dōngxi", cat: "Phrases" },
    { en: "to go to school to take class", zh: "去学校上课", py: "qù xuéxiào shàngkè", cat: "Phrases" },
    { en: "to go to the library to read books", zh: "去图书馆看书", py: "qù túshūguǎn kàn shū", cat: "Phrases" },
    { en: "to go to the bank to withdraw money", zh: "去银行取钱", py: "qù yínháng qǔ qián", cat: "Phrases" },
    { en: "to go home to eat", zh: "回家吃饭", py: "huí jiā chīfàn", cat: "Phrases" },
    { en: "to go back to the dorm to sleep", zh: "回宿舍睡觉", py: "huí sùshè shuìjiào", cat: "Phrases" },
    // Useful sentences
    { en: "The schoolbag is under the table.", zh: "书包在桌子下面。", py: "Shūbāo zài zhuōzi xiàmiàn.", cat: "Sentences" },
    { en: "I can speak a little Chinese.", zh: "我会说一点点中文。", py: "Wǒ huì shuō yìdiǎndian Zhōngwén.", cat: "Sentences" },
    { en: "How much is this cup?", zh: "这个杯子多少钱？", py: "Zhè ge bēizi duōshǎo qián?", cat: "Sentences" },
    { en: "Too expensive! A little cheaper, OK?", zh: "太贵了！便宜点儿，好吗？", py: "Tài guì le! Piányi diǎnr, hǎo ma?", cat: "Sentences" },
    { en: "May I sit here?", zh: "我能坐这儿吗？", py: "Wǒ néng zuò zhèr ma?", cat: "Sentences" },
    { en: "Let's go eat tomorrow!", zh: "我们明天去吃饭吧！", py: "Wǒmen míngtiān qù chīfàn ba!", cat: "Sentences" },
    { en: "Excuse me / sorry", zh: "不好意思", py: "bù hǎo yìsi", cat: "Sentences" },
  ],

  // ===== 39 Q&A dialogues from lessons 6-10 (also used for Part 2 listening) =====
  dialogues: [
    { topic: "Abilities (会)", q: { zh: "你会唱歌吗？", py: "Nǐ huì chànggē ma?", en: "Can you sing?" }, a: { zh: "我会唱歌。", py: "Wǒ huì chànggē.", en: "I can sing." } },
    { topic: "Abilities (会)", q: { zh: "马克，你会唱歌吗？", py: "Mǎkè, nǐ huì chànggē ma?", en: "Mark, can you sing?" }, a: { zh: "我也会唱歌。", py: "Wǒ yě huì chànggē.", en: "I can also sing." } },
    { topic: "Abilities (会)", q: { zh: "你会开车吗？", py: "Nǐ huì kāichē ma?", en: "Can you drive?" }, a: { zh: "我不会开车。", py: "Wǒ bú huì kāichē.", en: "I can't drive." } },
    { topic: "Abilities (会)", q: { zh: "你会说中文吗？", py: "Nǐ huì shuō Zhōngwén ma?", en: "Can you speak Chinese?" }, a: { zh: "不好意思，我的中文不好。", py: "Bù hǎo yìsi, wǒ de Zhōngwén bù hǎo.", en: "Sorry, my Chinese is not good." } },
    { topic: "Abilities (会)", q: { zh: "你会说中文吗？", py: "Nǐ huì shuō Zhōngwén ma?", en: "Can you speak Chinese?" }, a: { zh: "我会说一点点中文。", py: "Wǒ huì shuō yìdiǎndian Zhōngwén.", en: "I can speak a little Chinese." } },
    { topic: "Abilities (会)", q: { zh: "你会说什么语言？", py: "Nǐ huì shuō shénme yǔyán?", en: "What languages can you speak?" }, a: { zh: "我会说土耳其语、英语和一点点中文。", py: "Wǒ huì shuō Tǔ'ěrqíyǔ, Yīngyǔ hé yìdiǎndian Zhōngwén.", en: "I can speak Turkish, English and a little Chinese." } },
    { topic: "Abilities (会)", q: { zh: "你会写汉字吗？", py: "Nǐ huì xiě Hànzì ma?", en: "Can you write Chinese characters?" }, a: { zh: "我会写一些汉字。", py: "Wǒ huì xiě yìxiē Hànzì.", en: "I can write some characters." } },
    { topic: "How to say (怎么)", q: { zh: "这个字怎么读？", py: "Zhè ge zì zěnme dú?", en: "How is this character read?" }, a: { zh: "人。", py: "Rén.", en: "Rén (person)." } },
    { topic: "How to say (怎么)", q: { zh: "这个字怎么写？", py: "Zhè ge zì zěnme xiě?", en: "How is this character written?" }, a: { zh: "撇、捺。/ 不好意思，我不会写。", py: "Piě, nà. / Bù hǎo yìsi, wǒ bú huì xiě.", en: "Left-stroke, right-stroke. / Sorry, I can't write it." } },
    { topic: "How to say (怎么)", q: { zh: "“water” 用中文怎么说？", py: "“water” yòng Zhōngwén zěnme shuō?", en: "How do you say “water” in Chinese?" }, a: { zh: "水。", py: "Shuǐ.", en: "Shuǐ." } },
    { topic: "Food & Drink", q: { zh: "你饿吗？", py: "Nǐ è ma?", en: "Are you hungry?" }, a: { zh: "我很饿。/ 我不饿。", py: "Wǒ hěn è. / Wǒ bú è.", en: "I'm very hungry. / I'm not hungry." } },
    { topic: "Food & Drink", q: { zh: "土耳其菜好吃吗？", py: "Tǔ'ěrqí cài hǎochī ma?", en: "Is Turkish food tasty?" }, a: { zh: "土耳其菜很好吃。", py: "Tǔ'ěrqí cài hěn hǎochī.", en: "Turkish food is very tasty." } },
    { topic: "Food & Drink", q: { zh: "你喜欢吃什么？", py: "Nǐ xǐhuan chī shénme?", en: "What do you like to eat?" }, a: { zh: "我喜欢吃披萨。", py: "Wǒ xǐhuan chī pīsà.", en: "I like to eat pizza." } },
    { topic: "Food & Drink", q: { zh: "咖啡好喝吗？", py: "Kāfēi hǎohē ma?", en: "Is coffee good (to drink)?" }, a: { zh: "咖啡不好喝。", py: "Kāfēi bù hǎohē.", en: "Coffee is not good." } },
    { topic: "Food & Drink", q: { zh: "你喜欢喝什么？", py: "Nǐ xǐhuan hē shénme?", en: "What do you like to drink?" }, a: { zh: "我喜欢喝水。", py: "Wǒ xǐhuan hē shuǐ.", en: "I like to drink water." } },
    { topic: "Dates & Time", q: { zh: "今年是多少年？", py: "Jīnnián shì duōshǎo nián?", en: "What year is this year?" }, a: { zh: "今年是2026年。", py: "Jīnnián shì èr líng èr liù nián.", en: "This year is 2026." } },
    { topic: "Dates & Time", q: { zh: "这个月是几月？", py: "Zhè ge yuè shì jǐ yuè?", en: "What month is this month?" }, a: { zh: "这个月是6月。", py: "Zhè ge yuè shì liù yuè.", en: "This month is June." } },
    { topic: "Dates & Time", q: { zh: "今天几号？", py: "Jīntiān jǐ hào?", en: "What's the date today?" }, a: { zh: "今天6月16号。", py: "Jīntiān liù yuè shíliù hào.", en: "Today is June 16th." } },
    { topic: "Dates & Time", q: { zh: "今天星期几？", py: "Jīntiān xīngqī jǐ?", en: "What day is it today?" }, a: { zh: "今天星期二。", py: "Jīntiān xīngqī'èr.", en: "Today is Tuesday." } },
    { topic: "Dates & Time", q: { zh: "你的生日是什么时候？", py: "Nǐ de shēngrì shì shénme shíhou?", en: "When is your birthday?" }, a: { zh: "我的生日是7月15号。", py: "Wǒ de shēngrì shì qī yuè shíwǔ hào.", en: "My birthday is July 15th." } },
    { topic: "Dates & Time", q: { zh: "中文考试是几月几号？", py: "Zhōngwén kǎoshì shì jǐ yuè jǐ hào?", en: "What date is the Chinese exam?" }, a: { zh: "中文考试是6月16号。", py: "Zhōngwén kǎoshì shì liù yuè shíliù hào.", en: "The Chinese exam is June 16th." } },
    { topic: "Dates & Time", q: { zh: "你什么时候上中文课？", py: "Nǐ shénme shíhou shàng Zhōngwén kè?", en: "When do you have Chinese class?" }, a: { zh: "我星期一和星期三上中文课。", py: "Wǒ xīngqīyī hé xīngqīsān shàng Zhōngwén kè.", en: "I have Chinese class on Monday and Wednesday." } },
    { topic: "Dates & Time", q: { zh: "一年有几个月？", py: "Yì nián yǒu jǐ ge yuè?", en: "How many months are in a year?" }, a: { zh: "一年有12个月。", py: "Yì nián yǒu shí'èr ge yuè.", en: "A year has 12 months." } },
    { topic: "Dates & Time", q: { zh: "一个星期有几天？", py: "Yí ge xīngqī yǒu jǐ tiān?", en: "How many days are in a week?" }, a: { zh: "一个星期有7天。", py: "Yí ge xīngqī yǒu qī tiān.", en: "A week has 7 days." } },
    { topic: "Going places (去)", q: { zh: "你去哪儿？", py: "Nǐ qù nǎr?", en: "Where are you going?" }, a: { zh: "我去学校。", py: "Wǒ qù xuéxiào.", en: "I'm going to school." } },
    { topic: "Going places (去)", q: { zh: "你去学校做什么？", py: "Nǐ qù xuéxiào zuò shénme?", en: "What do you go to school to do?" }, a: { zh: "我去学校上课。", py: "Wǒ qù xuéxiào shàngkè.", en: "I go to school to take class." } },
    { topic: "Going places (去)", q: { zh: "星期三你想去哪儿？", py: "Xīngqīsān nǐ xiǎng qù nǎr?", en: "Where do you want to go on Wednesday?" }, a: { zh: "我想去超市买东西。", py: "Wǒ xiǎng qù chāoshì mǎi dōngxi.", en: "I want to go to the supermarket to buy things." } },
    { topic: "Shopping", q: { zh: "你想买什么？", py: "Nǐ xiǎng mǎi shénme?", en: "What do you want to buy?" }, a: { zh: "我想买一个杯子。", py: "Wǒ xiǎng mǎi yí ge bēizi.", en: "I want to buy a cup." } },
    { topic: "Shopping", q: { zh: "这个杯子多少钱？", py: "Zhè ge bēizi duōshǎo qián?", en: "How much is this cup?" }, a: { zh: "18块钱。", py: "Shíbā kuài qián.", en: "18 kuai." } },
    { topic: "Shopping", q: { zh: "太贵了！便宜点儿，好吗？", py: "Tài guì le! Piányi diǎnr, hǎo ma?", en: "Too expensive! A little cheaper, OK?" }, a: { zh: "好的。", py: "Hǎo de.", en: "OK." } },
    { topic: "Location (在/有)", q: { zh: "书包在哪儿？", py: "Shūbāo zài nǎr?", en: "Where is the schoolbag?" }, a: { zh: "书包在桌子下面。", py: "Shūbāo zài zhuōzi xiàmiàn.", en: "The schoolbag is under the table." } },
    { topic: "Location (在/有)", q: { zh: "小猫在桌子下面吗？", py: "Xiǎomāo zài zhuōzi xiàmiàn ma?", en: "Is the kitten under the table?" }, a: { zh: "小猫不在桌子下面。", py: "Xiǎomāo bú zài zhuōzi xiàmiàn.", en: "The kitten is not under the table." } },
    { topic: "Location (在/有)", q: { zh: "桌子上面有什么？", py: "Zhuōzi shàngmiàn yǒu shénme?", en: "What is on the table?" }, a: { zh: "桌子上面有一个书包。", py: "Zhuōzi shàngmiàn yǒu yí ge shūbāo.", en: "There is a schoolbag on the table." } },
    { topic: "Location (在/有)", q: { zh: "你爸爸在家吗？", py: "Nǐ bàba zài jiā ma?", en: "Is your dad at home?" }, a: { zh: "他不在家。", py: "Tā bú zài jiā.", en: "He is not at home." } },
    { topic: "Work (工作)", q: { zh: "你在哪儿工作？", py: "Nǐ zài nǎr gōngzuò?", en: "Where do you work?" }, a: { zh: "我是医生，在医院工作。", py: "Wǒ shì yīshēng, zài yīyuàn gōngzuò.", en: "I'm a doctor; I work at a hospital." } },
    { topic: "Work (工作)", q: { zh: "你在哪儿工作？", py: "Nǐ zài nǎr gōngzuò?", en: "Where do you work?" }, a: { zh: "我是学生，不工作。", py: "Wǒ shì xuéshēng, bù gōngzuò.", en: "I'm a student; I don't work." } },
    { topic: "Permission (能)", q: { zh: "我能坐这儿吗？", py: "Wǒ néng zuò zhèr ma?", en: "May I sit here?" }, a: { zh: "请坐。", py: "Qǐng zuò.", en: "Please sit." } },
    { topic: "Permission (能)", q: { zh: "我能用你的笔吗？", py: "Wǒ néng yòng nǐ de bǐ ma?", en: "May I use your pen?" }, a: { zh: "好的。", py: "Hǎo de.", en: "OK." } },
    { topic: "Permission (能)", q: { zh: "我能看你的手机吗？", py: "Wǒ néng kàn nǐ de shǒujī ma?", en: "May I look at your phone?" }, a: { zh: "不好意思，不能。", py: "Bù hǎo yìsi, bù néng.", en: "Sorry, you may not." } },
    { topic: "Suggestions (吧)", q: { zh: "我们明天去吃饭吧！", py: "Wǒmen míngtiān qù chīfàn ba!", en: "Let's go eat tomorrow!" }, a: { zh: "好啊！", py: "Hǎo a!", en: "Sure!" } },
    { topic: "Suggestions (吧)", q: { zh: "你想去哪个饭店吃饭？", py: "Nǐ xiǎng qù nǎ ge fàndiàn chīfàn?", en: "Which restaurant do you want to eat at?" }, a: { zh: "我们去 BIG CHEFS 吧！", py: "Wǒmen qù BIG CHEFS ba!", en: "Let's go to BIG CHEFS!" } },
    { topic: "Suggestions (吧)", q: { zh: "你喜欢哪个咖啡店？", py: "Nǐ xǐhuan nǎ ge kāfēi diàn?", en: "Which coffee shop do you like?" }, a: { zh: "我喜欢 Starbucks。", py: "Wǒ xǐhuan Starbucks.", en: "I like Starbucks." } },
    { topic: "Suggestions (吧)", q: { zh: "你是哪个老师的学生？", py: "Nǐ shì nǎ ge lǎoshī de xuéshēng?", en: "Which teacher's student are you?" }, a: { zh: "我是王老师的学生。", py: "Wǒ shì Wáng lǎoshī de xuéshēng.", en: "I'm Teacher Wang's student." } },
    { topic: "Suggestions (吧)", q: { zh: "我们明天去打篮球吧！", py: "Wǒmen míngtiān qù dǎ lánqiú ba!", en: "Let's play basketball tomorrow!" }, a: { zh: "不好意思，我不想去打篮球。", py: "Bù hǎo yìsi, wǒ bù xiǎng qù dǎ lánqiú.", en: "Sorry, I don't want to play basketball." } },
  ],

  // ===== PART 3: statement -> make the question =====
  part3: [
    { s: { zh: "今天星期五。", py: "Jīntiān xīngqīwǔ.", en: "Today is Friday." }, q: [{ zh: "今天星期几？", py: "Jīntiān xīngqī jǐ?", en: "What day is it today?" }], hint: "Day of the week → 星期几" },
    { s: { zh: "我喜欢吃汉堡。", py: "Wǒ xǐhuan chī hànbǎo.", en: "I like to eat hamburgers." }, q: [{ zh: "你喜欢吃什么？", py: "Nǐ xǐhuan chī shénme?", en: "What do you like to eat?" }], hint: "Thing → 什么" },
    { s: { zh: "书包在桌子上面。", py: "Shūbāo zài zhuōzi shàngmiàn.", en: "The schoolbag is on the table." }, q: [{ zh: "书包在哪儿？", py: "Shūbāo zài nǎr?", en: "Where is the schoolbag?" }], hint: "Place → 哪儿" },
    { s: { zh: "我会游泳。", py: "Wǒ huì yóuyǒng.", en: "I can swim." }, q: [{ zh: "你会游泳吗？", py: "Nǐ huì yóuyǒng ma?", en: "Can you swim?" }, { zh: "你会什么？", py: "Nǐ huì shénme?", en: "What can you do?" }], hint: "Yes/no → 吗" },
    { s: { zh: "我的生日是5月23号。", py: "Wǒ de shēngrì shì wǔ yuè èrshísān hào.", en: "My birthday is May 23rd." }, q: [{ zh: "你的生日是什么时候？", py: "Nǐ de shēngrì shì shénme shíhou?", en: "When is your birthday?" }, { zh: "你的生日是几月几号？", py: "Nǐ de shēngrì shì jǐ yuè jǐ hào?", en: "What date is your birthday?" }], hint: "Time → 什么时候 / 几月几号" },
    { s: { zh: "今年是2026年。", py: "Jīnnián shì èr líng èr liù nián.", en: "This year is 2026." }, q: [{ zh: "今年是多少年？", py: "Jīnnián shì duōshǎo nián?", en: "What year is this year?" }], hint: "Year → 多少年" },
    { s: { zh: "这个月是6月。", py: "Zhè ge yuè shì liù yuè.", en: "This month is June." }, q: [{ zh: "这个月是几月？", py: "Zhè ge yuè shì jǐ yuè?", en: "What month is this month?" }], hint: "Month → 几月" },
    { s: { zh: "今天6月16号。", py: "Jīntiān liù yuè shíliù hào.", en: "Today is June 16th." }, q: [{ zh: "今天几号？", py: "Jīntiān jǐ hào?", en: "What's the date today?" }], hint: "Date → 几号" },
    { s: { zh: "我喜欢喝茶。", py: "Wǒ xǐhuan hē chá.", en: "I like to drink tea." }, q: [{ zh: "你喜欢喝什么？", py: "Nǐ xǐhuan hē shénme?", en: "What do you like to drink?" }], hint: "Thing → 什么" },
    { s: { zh: "我会说土耳其语和英语。", py: "Wǒ huì shuō Tǔ'ěrqíyǔ hé Yīngyǔ.", en: "I can speak Turkish and English." }, q: [{ zh: "你会说什么语言？", py: "Nǐ huì shuō shénme yǔyán?", en: "What languages can you speak?" }], hint: "Languages → 什么语言" },
    { s: { zh: "这个杯子18块钱。", py: "Zhè ge bēizi shíbā kuài qián.", en: "This cup is 18 kuai." }, q: [{ zh: "这个杯子多少钱？", py: "Zhè ge bēizi duōshǎo qián?", en: "How much is this cup?" }], hint: "Price → 多少钱" },
    { s: { zh: "我去超市买东西。", py: "Wǒ qù chāoshì mǎi dōngxi.", en: "I go to the supermarket to buy things." }, q: [{ zh: "你去哪儿？", py: "Nǐ qù nǎr?", en: "Where are you going?" }, { zh: "你去超市做什么？", py: "Nǐ qù chāoshì zuò shénme?", en: "What do you go to the supermarket to do?" }], hint: "Place → 哪儿；purpose → 做什么" },
    { s: { zh: "我是医生，在医院工作。", py: "Wǒ shì yīshēng, zài yīyuàn gōngzuò.", en: "I'm a doctor; I work at a hospital." }, q: [{ zh: "你在哪儿工作？", py: "Nǐ zài nǎr gōngzuò?", en: "Where do you work?" }], hint: "Workplace → 在哪儿工作" },
    { s: { zh: "一年有12个月。", py: "Yì nián yǒu shí'èr ge yuè.", en: "A year has 12 months." }, q: [{ zh: "一年有几个月？", py: "Yì nián yǒu jǐ ge yuè?", en: "How many months are in a year?" }], hint: "Small number → 几" },
    { s: { zh: "一个星期有7天。", py: "Yí ge xīngqī yǒu qī tiān.", en: "A week has 7 days." }, q: [{ zh: "一个星期有几天？", py: "Yí ge xīngqī yǒu jǐ tiān?", en: "How many days are in a week?" }], hint: "Small number → 几" },
    { s: { zh: "桌子上面有一个书包。", py: "Zhuōzi shàngmiàn yǒu yí ge shūbāo.", en: "There is a schoolbag on the table." }, q: [{ zh: "桌子上面有什么？", py: "Zhuōzi shàngmiàn yǒu shénme?", en: "What is on the table?" }], hint: "Thing → 有什么" },
    { s: { zh: "我星期一和星期三上中文课。", py: "Wǒ xīngqīyī hé xīngqīsān shàng Zhōngwén kè.", en: "I have Chinese class on Monday and Wednesday." }, q: [{ zh: "你什么时候上中文课？", py: "Nǐ shénme shíhou shàng Zhōngwén kè?", en: "When do you have Chinese class?" }], hint: "Time → 什么时候" },
    { s: { zh: "中文考试是6月16号。", py: "Zhōngwén kǎoshì shì liù yuè shíliù hào.", en: "The Chinese exam is June 16th." }, q: [{ zh: "中文考试是几月几号？", py: "Zhōngwén kǎoshì shì jǐ yuè jǐ hào?", en: "What date is the Chinese exam?" }], hint: "Date → 几月几号" },
    { s: { zh: "我是王老师的学生。", py: "Wǒ shì Wáng lǎoshī de xuéshēng.", en: "I'm Teacher Wang's student." }, q: [{ zh: "你是哪个老师的学生？", py: "Nǐ shì nǎ ge lǎoshī de xuéshēng?", en: "Which teacher's student are you?" }], hint: "Which one → 哪个" },
    { s: { zh: "我想买一个杯子。", py: "Wǒ xiǎng mǎi yí ge bēizi.", en: "I want to buy a cup." }, q: [{ zh: "你想买什么？", py: "Nǐ xiǎng mǎi shénme?", en: "What do you want to buy?" }], hint: "Thing → 什么" },
    { s: { zh: "我去学校上课。", py: "Wǒ qù xuéxiào shàngkè.", en: "I go to school to take class." }, q: [{ zh: "你去学校做什么？", py: "Nǐ qù xuéxiào zuò shénme?", en: "What do you go to school to do?" }], hint: "Purpose → 做什么" },
    { s: { zh: "小猫不在桌子下面。", py: "Xiǎomāo bú zài zhuōzi xiàmiàn.", en: "The kitten is not under the table." }, q: [{ zh: "小猫在桌子下面吗？", py: "Xiǎomāo zài zhuōzi xiàmiàn ma?", en: "Is the kitten under the table?" }], hint: "Yes/no → 吗" },
  ],

  // ===== PART 4: monologue topics with model answers =====
  monologues: [
    {
      title: "My Weekly Plan", titleZh: "介绍你的周计划", titlePy: "Jièshào nǐ de zhōu jìhuà",
      tip: "Pattern: 我 + 星期X + 上午去…，下午去… Use 去 + place + purpose verbs (上课、买东西、看书、取钱…).",
      lines: [
        { zh: "我介绍我的周计划。", py: "Wǒ jièshào wǒ de zhōu jìhuà.", en: "Let me introduce my weekly plan." },
        { zh: "我星期一上午去学校上课，下午去图书馆看书。", py: "Wǒ xīngqīyī shàngwǔ qù xuéxiào shàngkè, xiàwǔ qù túshūguǎn kàn shū.", en: "On Monday morning I go to school for class; in the afternoon I go to the library to read." },
        { zh: "我星期二上午去教室写作业，下午去咖啡店喝咖啡。", py: "Wǒ xīngqī'èr shàngwǔ qù jiàoshì xiě zuòyè, xiàwǔ qù kāfēi diàn hē kāfēi.", en: "On Tuesday morning I do homework in the classroom; in the afternoon I drink coffee at a café." },
        { zh: "我星期三上午去超市买东西，下午和朋友去饭店吃饭。", py: "Wǒ xīngqīsān shàngwǔ qù chāoshì mǎi dōngxi, xiàwǔ hé péngyou qù fàndiàn chīfàn.", en: "On Wednesday morning I go to the supermarket to shop; in the afternoon I eat at a restaurant with friends." },
        { zh: "我星期四上午去学校上中文课，下午去银行取钱。", py: "Wǒ xīngqīsì shàngwǔ qù xuéxiào shàng Zhōngwén kè, xiàwǔ qù yínháng qǔ qián.", en: "On Thursday morning I have Chinese class; in the afternoon I withdraw money at the bank." },
        { zh: "我星期五上午去学校上课，下午去游泳。", py: "Wǒ xīngqīwǔ shàngwǔ qù xuéxiào shàngkè, xiàwǔ qù yóuyǒng.", en: "On Friday morning I go to class; in the afternoon I go swimming." },
        { zh: "我星期六上午去打篮球，下午回家吃饭。", py: "Wǒ xīngqīliù shàngwǔ qù dǎ lánqiú, xiàwǔ huí jiā chīfàn.", en: "On Saturday morning I play basketball; in the afternoon I go home to eat." },
        { zh: "我星期天上午看书，下午回宿舍睡觉。", py: "Wǒ xīngqītiān shàngwǔ kàn shū, xiàwǔ huí sùshè shuìjiào.", en: "On Sunday morning I read; in the afternoon I go back to the dorm to sleep." },
      ],
    },
    {
      title: "My Friend", titleZh: "介绍你的朋友", titlePy: "Jièshào nǐ de péngyou",
      tip: "Cover: name, age, birthday, nationality, family, abilities (会…), likes (喜欢…), school/work.",
      lines: [
        { zh: "这个人是我的朋友，他叫马克。", py: "Zhè ge rén shì wǒ de péngyou, tā jiào Mǎkè.", en: "This person is my friend; his name is Mark." },
        { zh: "他22岁了，他的生日是7月8号。他是土耳其人。", py: "Tā èrshí'èr suì le, tā de shēngrì shì qī yuè bā hào. Tā shì Tǔ'ěrqí rén.", en: "He is 22; his birthday is July 8th. He is Turkish." },
        { zh: "他家有4口人：他爸爸妈妈、一个姐姐和他。", py: "Tā jiā yǒu sì kǒu rén: tā bàba māma, yí ge jiějie hé tā.", en: "His family has 4 people: his parents, an older sister, and him." },
        { zh: "他会唱歌、跳舞和开车。", py: "Tā huì chànggē, tiàowǔ hé kāichē.", en: "He can sing, dance and drive." },
        { zh: "他会说土耳其语、英语和一点点中文，他也会写一点点汉字。", py: "Tā huì shuō Tǔ'ěrqíyǔ, Yīngyǔ hé yìdiǎndian Zhōngwén, tā yě huì xiě yìdiǎndian Hànzì.", en: "He speaks Turkish, English and a little Chinese; he can also write a few characters." },
        { zh: "他喜欢吃土耳其菜，喜欢喝咖啡。", py: "Tā xǐhuan chī Tǔ'ěrqí cài, xǐhuan hē kāfēi.", en: "He likes Turkish food and likes coffee." },
        { zh: "他星期二和星期四去学校上中文课。他喜欢中文。", py: "Tā xīngqī'èr hé xīngqīsì qù xuéxiào shàng Zhōngwén kè. Tā xǐhuan Zhōngwén.", en: "He has Chinese class on Tuesday and Thursday. He likes Chinese." },
        { zh: "他是中东技术大学的学生，不工作。", py: "Tā shì Zhōngdōng Jìshù Dàxué de xuéshēng, bù gōngzuò.", en: "He is a student at Middle East Technical University; he doesn't work." },
      ],
    },
    {
      title: "My Wallet", titleZh: "介绍你的钱包", titlePy: "Jièshào nǐ de qiánbāo",
      tip: "Pattern: 钱包里面有 + amounts with measure words (块钱、张…). This is the Part 4 question on the sample paper!",
      lines: [
        { zh: "我介绍我的钱包。", py: "Wǒ jièshào wǒ de qiánbāo.", en: "Let me introduce my wallet." },
        { zh: "钱包里面有700块钱、3张银行卡和1张照片。", py: "Qiánbāo lǐmiàn yǒu qībǎi kuài qián, sān zhāng yínháng kǎ hé yì zhāng zhàopiàn.", en: "Inside the wallet there are 700 kuai, 3 bank cards and 1 photo." },
        { zh: "钱包里面也有一张身份证和一张驾照。", py: "Qiánbāo lǐmiàn yě yǒu yì zhāng shēnfènzhèng hé yì zhāng jiàzhào.", en: "There is also an ID card and a driver's license." },
        { zh: "还有一张交通卡和一张校园卡。", py: "Hái yǒu yì zhāng jiāotōng kǎ hé yì zhāng xiàoyuán kǎ.", en: "There is also a transport card and a campus card." },
        { zh: "我非常喜欢我的钱包。", py: "Wǒ fēicháng xǐhuan wǒ de qiánbāo.", en: "I really like my wallet." },
      ],
    },
    {
      title: "My Room", titleZh: "介绍你的房间", titlePy: "Jièshào nǐ de fángjiān",
      tip: "Pattern: place + position word (上面/左面/前面/里面) + 有 + object. Practice the position words!",
      lines: [
        { zh: "我介绍我的房间。", py: "Wǒ jièshào wǒ de fángjiān.", en: "Let me introduce my room." },
        { zh: "我的房间里面有一张床，", py: "Wǒ de fángjiān lǐmiàn yǒu yì zhāng chuáng,", en: "In my room there is a bed," },
        { zh: "床上面有一个枕头和一个被子。", py: "chuáng shàngmiàn yǒu yí ge zhěntou hé yí ge bèizi.", en: "on the bed there is a pillow and a quilt." },
        { zh: "床左面有一个桌子，", py: "Chuáng zuǒmiàn yǒu yí ge zhuōzi,", en: "To the left of the bed there is a desk," },
        { zh: "桌子上面有一些书，", py: "zhuōzi shàngmiàn yǒu yìxiē shū,", en: "on the desk there are some books," },
        { zh: "桌子前面有一把椅子。", py: "zhuōzi qiánmiàn yǒu yì bǎ yǐzi.", en: "in front of the desk there is a chair." },
        { zh: "桌子左面有一个衣柜，", py: "Zhuōzi zuǒmiàn yǒu yí ge yīguì,", en: "To the left of the desk there is a wardrobe," },
        { zh: "衣柜里面有很多漂亮的衣服。", py: "yīguì lǐmiàn yǒu hěn duō piàoliang de yīfu.", en: "inside the wardrobe there are many pretty clothes." },
        { zh: "我非常喜欢我的房间。", py: "Wǒ fēicháng xǐhuan wǒ de fángjiān.", en: "I really like my room." },
      ],
    },
  ],

  // Question-word cheat sheet shown on the Part 3 page
  questionWords: [
    { qw: "什么", py: "shénme", use: "what (things)", ex: "你喜欢吃什么？" },
    { qw: "什么时候", py: "shénme shíhou", use: "when (time)", ex: "你的生日是什么时候？" },
    { qw: "哪儿", py: "nǎr", use: "where (place)", ex: "书包在哪儿？" },
    { qw: "哪个", py: "nǎ ge", use: "which one", ex: "你是哪个老师的学生？" },
    { qw: "几", py: "jǐ", use: "how many (small numbers), dates", ex: "今天几号？一年有几个月？" },
    { qw: "多少", py: "duōshǎo", use: "how many/much (big numbers, price)", ex: "这个杯子多少钱？" },
    { qw: "星期几", py: "xīngqī jǐ", use: "what day of the week", ex: "今天星期几？" },
    { qw: "几月几号", py: "jǐ yuè jǐ hào", use: "what date", ex: "中文考试是几月几号？" },
    { qw: "吗", py: "ma", use: "yes/no question particle", ex: "你会游泳吗？" },
    { qw: "怎么", py: "zěnme", use: "how", ex: "这个字怎么读？" },
  ],

  // Word glossary for click-to-explain. word: [pinyin, meaning]
  glossary: {
    // pronouns & people
    "我": ["wǒ", "I, me"], "你": ["nǐ", "you"], "他": ["tā", "he, him"], "她": ["tā", "she, her"],
    "我们": ["wǒmen", "we, us"], "你们": ["nǐmen", "you (plural)"], "他们": ["tāmen", "they"],
    "人": ["rén", "person, people"], "朋友": ["péngyou", "friend"],
    "爸爸": ["bàba", "dad"], "妈妈": ["māma", "mom"], "姐姐": ["jiějie", "older sister"],
    "老师": ["lǎoshī", "teacher"], "学生": ["xuéshēng", "student"], "医生": ["yīshēng", "doctor"],
    "警察": ["jǐngchá", "police officer"], "售货员": ["shòuhuòyuán", "salesperson"], "服务员": ["fúwùyuán", "waiter, server"],
    "马克": ["Mǎkè", "Mark (a name)"], "王": ["Wáng", "Wang (a surname)"], "小猫": ["xiǎomāo", "kitten, cat"],
    // core verbs
    "是": ["shì", "to be (am/is/are)"], "在": ["zài", "to be at / in / on"], "有": ["yǒu", "to have; there is/are"],
    "叫": ["jiào", "to be called, named"], "说": ["shuō", "to speak, say"], "读": ["dú", "to read (aloud)"],
    "写": ["xiě", "to write"], "用": ["yòng", "to use; with"], "坐": ["zuò", "to sit"],
    "看": ["kàn", "to look, watch, read"], "做": ["zuò", "to do, make"], "买": ["mǎi", "to buy"],
    "去": ["qù", "to go (to)"], "回": ["huí", "to return, go back"], "吃": ["chī", "to eat"], "喝": ["hē", "to drink"],
    "会": ["huì", "can (learned skill)"], "能": ["néng", "can, may (permission)"],
    "想": ["xiǎng", "to want to, would like to"], "喜欢": ["xǐhuan", "to like"],
    "工作": ["gōngzuò", "to work; job"], "介绍": ["jièshào", "to introduce"],
    // adjectives & adverbs
    "饿": ["è", "hungry"], "贵": ["guì", "expensive"], "便宜": ["piányi", "cheap"],
    "好": ["hǎo", "good; OK"], "好的": ["hǎo de", "OK, sure"], "好吗": ["hǎo ma", "...OK? alright?"],
    "好吃": ["hǎochī", "tasty (food)"], "好喝": ["hǎohē", "tasty (drinks)"],
    "很": ["hěn", "very"], "也": ["yě", "also, too"], "太": ["tài", "too (much)"],
    "非常": ["fēicháng", "very, extremely"], "漂亮": ["piàoliang", "pretty, beautiful"],
    "很多": ["hěn duō", "many, a lot of"], "多": ["duō", "many, much"],
    "一点点": ["yìdiǎndian", "a tiny bit"], "一些": ["yìxiē", "some"], "点儿": ["diǎnr", "a little"],
    // particles & function words
    "的": ["de", "possessive particle ('s)"], "不": ["bù", "not, no"],
    "吗": ["ma", "yes/no question particle"], "吧": ["ba", "suggestion particle (let's...)"],
    "啊": ["a", "exclamation particle"], "了": ["le", "particle: change / completed action"],
    "和": ["hé", "and; with"], "请": ["qǐng", "please"], "还有": ["hái yǒu", "in addition, there's also"],
    "还": ["hái", "still, also"], "不好意思": ["bù hǎo yìsi", "sorry, excuse me"],
    // question words
    "什么": ["shénme", "what"], "什么时候": ["shénme shíhou", "when"], "时候": ["shíhou", "time, moment"],
    "哪儿": ["nǎr", "where"], "哪个": ["nǎ ge", "which (one)"], "怎么": ["zěnme", "how"],
    "几": ["jǐ", "how many (small); which (date)"], "多少": ["duōshǎo", "how many, how much"],
    // numbers
    "一": ["yī", "one"], "二": ["èr", "two"], "三": ["sān", "three"], "四": ["sì", "four"], "五": ["wǔ", "five"],
    "六": ["liù", "six"], "七": ["qī", "seven"], "八": ["bā", "eight"], "九": ["jiǔ", "nine"], "十": ["shí", "ten"],
    // money & measure words
    "钱": ["qián", "money"], "块": ["kuài", "kuai (unit of money, like 'lira')"],
    "个": ["ge", "measure word (general)"], "张": ["zhāng", "measure word (flat things: cards, photos, beds)"],
    "把": ["bǎ", "measure word (things with handles: chairs, umbrellas)"], "支": ["zhī", "measure word (pens)"],
    "瓶": ["píng", "measure word (bottles)"], "本": ["běn", "measure word (books)"],
    "件": ["jiàn", "measure word (clothes)"], "口": ["kǒu", "measure word (family members)"],
    "岁": ["suì", "years old"],
    // time
    "年": ["nián", "year"], "月": ["yuè", "month"], "号": ["hào", "date, number (day of month)"],
    "天": ["tiān", "day"], "星期": ["xīngqī", "week"], "星期几": ["xīngqī jǐ", "which day of the week"],
    "星期一": ["xīngqīyī", "Monday"], "星期二": ["xīngqī'èr", "Tuesday"], "星期三": ["xīngqīsān", "Wednesday"],
    "星期四": ["xīngqīsì", "Thursday"], "星期五": ["xīngqīwǔ", "Friday"], "星期六": ["xīngqīliù", "Saturday"],
    "星期天": ["xīngqītiān", "Sunday"],
    "昨天": ["zuótiān", "yesterday"], "今天": ["jīntiān", "today"], "明天": ["míngtiān", "tomorrow"],
    "去年": ["qùnián", "last year"], "今年": ["jīnnián", "this year"], "明年": ["míngnián", "next year"],
    "上个月": ["shàng ge yuè", "last month"], "这个月": ["zhè ge yuè", "this month"], "下个月": ["xià ge yuè", "next month"],
    "上个星期": ["shàng ge xīngqī", "last week"], "这个星期": ["zhè ge xīngqī", "this week"], "下个星期": ["xià ge xīngqī", "next week"],
    "上午": ["shàngwǔ", "morning (a.m.)"], "下午": ["xiàwǔ", "afternoon (p.m.)"],
    "生日": ["shēngrì", "birthday"], "考试": ["kǎoshì", "exam"],
    // school & activities
    "课": ["kè", "class, lesson"], "中文课": ["Zhōngwén kè", "Chinese class"],
    "上课": ["shàngkè", "to attend class"], "上": ["shàng", "on, above; to attend"],
    "作业": ["zuòyè", "homework"], "写作业": ["xiě zuòyè", "to do homework"],
    "看书": ["kàn shū", "to read (books)"], "取钱": ["qǔ qián", "to withdraw money"],
    "睡觉": ["shuìjiào", "to sleep"], "买东西": ["mǎi dōngxi", "to buy things, go shopping"],
    "东西": ["dōngxi", "thing(s), stuff"], "吃饭": ["chīfàn", "to eat (a meal)"], "饭": ["fàn", "meal; rice"],
    "唱歌": ["chànggē", "to sing"], "跳舞": ["tiàowǔ", "to dance"], "开车": ["kāichē", "to drive"],
    "做饭": ["zuòfàn", "to cook"], "游泳": ["yóuyǒng", "to swim"],
    "打篮球": ["dǎ lánqiú", "to play basketball"], "踢足球": ["tī zúqiú", "to play football"],
    "篮球": ["lánqiú", "basketball"], "足球": ["zúqiú", "football"],
    "周计划": ["zhōu jìhuà", "weekly plan"], "计划": ["jìhuà", "plan"],
    // languages & writing
    "中文": ["Zhōngwén", "Chinese (language)"], "汉语": ["Hànyǔ", "Chinese (language)"],
    "汉字": ["Hànzì", "Chinese character(s)"], "字": ["zì", "character, word"],
    "语言": ["yǔyán", "language"], "英语": ["Yīngyǔ", "English"],
    "土耳其语": ["Tǔ'ěrqíyǔ", "Turkish (language)"], "土耳其菜": ["Tǔ'ěrqí cài", "Turkish food"],
    "土耳其人": ["Tǔ'ěrqí rén", "Turkish (person)"], "土耳其": ["Tǔ'ěrqí", "Turkey"],
    "法语": ["Fǎyǔ", "French"], "德语": ["Déyǔ", "German"], "西班牙语": ["Xībānyáyǔ", "Spanish"],
    "俄语": ["Éyǔ", "Russian"], "阿拉伯语": ["Ālābóyǔ", "Arabic"],
    "撇": ["piě", "left-falling stroke ㇒"], "捺": ["nà", "right-falling stroke ㇏"],
    // places
    "学校": ["xuéxiào", "school"], "超市": ["chāoshì", "supermarket"], "商店": ["shāngdiàn", "shop, store"],
    "教室": ["jiàoshì", "classroom"], "饭店": ["fàndiàn", "restaurant"], "咖啡店": ["kāfēi diàn", "coffee shop"],
    "图书馆": ["túshūguǎn", "library"], "银行": ["yínháng", "bank"], "家": ["jiā", "home; family"],
    "宿舍": ["sùshè", "dormitory"], "医院": ["yīyuàn", "hospital"], "警察局": ["jǐngchá jú", "police station"],
    "中东技术大学": ["Zhōngdōng Jìshù Dàxué", "Middle East Technical University (METU)"],
    "大学": ["dàxué", "university"], "房间": ["fángjiān", "room"],
    // objects
    "书包": ["shūbāo", "schoolbag"], "书": ["shū", "book"], "笔": ["bǐ", "pen"],
    "笔记本": ["bǐjìběn", "notebook"], "手机": ["shǒujī", "cellphone"], "杯子": ["bēizi", "cup, glass"],
    "伞": ["sǎn", "umbrella"], "衬衫": ["chènshān", "shirt"], "蛋糕": ["dàngāo", "cake"],
    "桌子": ["zhuōzi", "table, desk"], "椅子": ["yǐzi", "chair"], "床": ["chuáng", "bed"],
    "衣柜": ["yīguì", "wardrobe"], "枕头": ["zhěntou", "pillow"], "被子": ["bèizi", "quilt, blanket"],
    "衣服": ["yīfu", "clothes"],
    // wallet
    "钱包": ["qiánbāo", "wallet"], "照片": ["zhàopiàn", "photo"], "银行卡": ["yínháng kǎ", "bank card"],
    "身份证": ["shēnfènzhèng", "ID card"], "驾照": ["jiàzhào", "driver's license"],
    "交通卡": ["jiāotōng kǎ", "transport card"], "校园卡": ["xiàoyuán kǎ", "campus card"],
    // food & drink
    "水": ["shuǐ", "water"], "茶": ["chá", "tea"], "咖啡": ["kāfēi", "coffee"], "牛奶": ["niúnǎi", "milk"],
    "果汁": ["guǒzhī", "juice"], "可乐": ["kělè", "cola"], "啤酒": ["píjiǔ", "beer"], "红酒": ["hóngjiǔ", "red wine"],
    "寿司": ["shòusī", "sushi"], "面包": ["miànbāo", "bread"], "馒头": ["mántou", "steamed bun"],
    "米饭": ["mǐfàn", "rice (cooked)"], "牛排": ["niúpái", "steak"], "意面": ["yìmiàn", "pasta"],
    "面条儿": ["miàntiáor", "noodles"], "汉堡": ["hànbǎo", "hamburger"], "披萨": ["pīsà", "pizza"],
    "烤肉": ["kǎoròu", "roasted meat, kebab"], "菜": ["cài", "dish, cuisine; vegetable"],
    // positions
    "上面": ["shàngmiàn", "on top, above"], "下面": ["xiàmiàn", "under, below"],
    "前面": ["qiánmiàn", "in front"], "后面": ["hòumiàn", "behind"],
    "左面": ["zuǒmiàn", "left side"], "右面": ["yòumiàn", "right side"],
    "中间": ["zhōngjiān", "middle"], "里面": ["lǐmiàn", "inside"], "外面": ["wàimiàn", "outside"],
    // demonstratives
    "这": ["zhè", "this"], "这个": ["zhè ge", "this (one)"], "这儿": ["zhèr", "here"],
  },
};
